namespace StellarSyncShared.Metrics;

public class MetricsAPI
{
    public const string CounterInitializedConnections = "stellar_initialized_connections";
    public const string GaugeConnections = "stellar_connections";
    public const string GaugeAuthorizedConnections = "stellar_authorized_connections";
    public const string GaugeAvailableWorkerThreads = "stellar_available_threadpool";
    public const string GaugeAvailableIOWorkerThreads = "stellar_available_threadpool_io";
    public const string GaugeUsersRegistered = "stellar_users_registered";
    public const string CounterUsersRegisteredDeleted = "stellar_users_registered_deleted";
    public const string GaugePairs = "stellar_pairs";
    public const string GaugePairsPaused = "stellar_pairs_paused";
    public const string GaugeFilesTotal = "stellar_files";
    public const string GaugeFilesTotalColdStorage = "stellar_files_cold";
    public const string GaugeFilesTotalSize = "stellar_files_size";
    public const string GaugeFilesTotalSizeColdStorage = "stellar_files_size_cold";
    public const string GaugeFilesDownloadingFromCache = "stellar_files_downloading_from_cache";
    public const string GaugeFilesTasksWaitingForDownloadFromCache = "stellar_files_waiting_for_dl";
    public const string CounterUserPushData = "stellar_user_push";
    public const string CounterUserPushDataTo = "stellar_user_push_to";
    public const string CounterAuthenticationRequests = "stellar_auth_requests";
    public const string CounterAuthenticationCacheHits = "stellar_auth_requests_cachehit";
    public const string CounterAuthenticationFailures = "stellar_auth_requests_fail";
    public const string CounterAuthenticationSuccesses = "stellar_auth_requests_success";
    public const string GaugeAuthenticationCacheEntries = "stellar_auth_cache";
    public const string GaugeGroups = "stellar_groups";
    public const string GaugeGroupPairs = "stellar_groups_pairs";
    public const string GaugeFilesUniquePastHour = "stellar_files_unique_past_hour";
    public const string GaugeFilesUniquePastHourSize = "stellar_files_unique_past_hour_size";
    public const string GaugeFilesUniquePastDay = "stellar_files_unique_past_day";
    public const string GaugeFilesUniquePastDaySize = "stellar_files_unique_past_day_size";
    public const string GaugeCurrentDownloads = "stellar_current_downloads";
    public const string GaugeQueueFree = "stellar_download_queue_free";
    public const string GaugeQueueActive = "stellar_download_queue_active";
    public const string GaugeQueueInactive = "stellar_download_queue_inactive";
    public const string GaugeDownloadQueue = "stellar_download_queue";
    public const string GaugeDownloadQueueCancelled = "stellar_download_queue_cancelled";
    public const string GaugeDownloadPriorityQueue = "stellar_download_priority_queue";
    public const string GaugeDownloadPriorityQueueCancelled = "stellar_download_priority_queue_cancelled";
    public const string CounterFileRequests = "stellar_files_requests";
    public const string CounterFileRequestSize = "stellar_files_request_size";
    public const string CounterUserPairCacheHit = "stellar_pairscache_hit";
    public const string CounterUserPairCacheMiss = "stellar_pairscache_miss";
    public const string GaugeUserPairCacheUsers = "stellar_pairscache_users";
    public const string GaugeUserPairCacheEntries = "stellar_pairscache_entries";
    public const string CounterUserPairCacheNewEntries = "stellar_pairscache_new_entries";
    public const string CounterUserPairCacheUpdatedEntries = "stellar_pairscache_updated_entries";
    public const string GaugeGposeLobbies = "stellar_gpose_lobbies";
    public const string GaugeGposeLobbyUsers = "stellar_gpose_lobby_users";
    public const string GaugeHubConcurrency = "stellar_free_concurrent_hub_calls";
    public const string GaugeHubQueuedConcurrency = "stellar_free_concurrent_queued_hub_calls";
}